### ISSUE TITLE
Contact form submission error

### ISSUE THREAD

**Issue by deeprave** [totaljs/emptyproject-website#2]
I am seeing the following after submitting the contact form.

`======= 2020-07-13 00:45:53: api ---> TypeError: Cannot read property 'length' of undefined (http://192.168.63.34:8001/api/contact/) TypeError: Cannot read property 'length' of undefined
    at Message.to (/Users/davidn/Projects/totaljs/website/node_modules/total.js/mail.js:217:22)
    at Framework.F.onMail (/Users/davidn/Projects/totaljs/website/node_modules/total.js/index.js:6301:11)
    at global.LOGMAIL.F.logmail (/Users/davidn/Projects/totaljs/website/node_modules/total.js/index.js:6464:11)
    at SchemaBuilderEntity.onSave (/Users/davidn/Projects/totaljs/website/models/contact.js:34:3)
    at /Users/davidn/Projects/totaljs/website/node_modules/total.js/builders.js:1716:16
    at SchemaBuilderEntityProto.$prepare (/Users/davidn/Projects/totaljs/website/node_modules/total.js/builders.js:2143:3)
    at SchemaBuilderEntityProto.execute (/Users/davidn/Projects/totaljs/website/node_modules/total.js/builders.js:1684:7)
    at SchemaBuilderEntityProto.save (/Users/davidn/Projects/totaljs/website/node_modules/total.js/builders.js:1610:14)
    at SchemaBuilderEntity.CurrentSchemaInstance.SchemaInstance.$save (/Users/davidn/Projects/totaljs/website/node_modules/total.js/builders.js:3841:17)
    at ControllerProto.$save (/Users/davidn/Projects/totaljs/website/node_modules/total.js/index.js:11930:13)`

database/contactforms.nosql is correctly updated.

Node version: 14.4.0
Total.js version: 3.4.5

(probably a configuration issue)

**Comment by deeprave** [comment]
Just a followup, this seems to be a left-over from the last commit where "mail-contact" was changed to "mail_contact" in the configuration form, and models/contact.js was not updated accordingly.

**Comment by petersirka** [comment]
Thank you.
